### ISSUE TITLE
Smart Widget Chat Bot integratie in antwerpen.be/Subsidies - aanspreking spontaan opstarten

### ISSUE THREAD

**Issue by StevenGrysolle** [digipolisantwerp/chatbot_widget_ng1#4]
De begintekst zien we wel op DEV en ACC in de chatbot Engine.
Bij de intro in de subsidies pagina via de smmart widget is de aanspreking verdwenen.
In het filmpje moeten we de openingszin uitlokken door zelf “hallo” te zeggen.
[Chat bot widget gedrag.zip](https://github.com/digipolisantwerp/chatbot_widget_ng1/files/2232328/Chat.bot.widget.gedrag.zip)
https://jira.antwerpen.be/browse/ASTAD-23444

**Comment by jsebrech** [comment]
De chatbot demo geïntegreerd in de chatbot authoring omgeving stuurt altijd eerst een onzichtbaar bericht met daarin de lege string naar de server, en de reply daarop is de openingszin. Als de openingszin zelf de lege string is gaat die niet getoond worden. 

De chatbot API staat niet toe dat we een lege string sturen (geeft HTTP 400 error). De oplossing blijkt te zijn van bij initieel tonen een verborgen bericht met " " (spatie) te sturen en dan krijg je de openingszin terug.

De chatbot widget moet lege berichten negeren en niet tonen (om de lege openingszin correct af te handelen).
