### ISSUE TITLE
Smart Widget Chat Bot integratie in antwerpen.be/Subsidies - mobile version

### ISSUE THREAD

**Issue by StevenGrysolle** [digipolisantwerp/chatbot_widget_ng1#5]
Bij de mobile Version;
Als het chat venster gestart wordt,
=> als ik naar onder swipe komt de URL balk bovenaan mijn scherm tevoorschijn.
=> als ik naar boven swipe komt er onderaan mijn scherm een klein horizontaal balkje op mijn GSM-scherm tevoorschijn, waarbinnen de gehele websitecontent up/downscrolt .
https://jira.antwerpen.be/browse/ASTAD-23444

**Comment by jsebrech** [comment]
The specific question is to have an ability to have the height parameter as an expression (using "=" binding instead of "@" binding, as described here: http://blog.krawaller.se/posts/dissecting-bindings-in-angularjs/ )
