### ISSUE TITLE
UX: de knoppen in de chat sessie LINKS uitvullen.

### ISSUE THREAD

**Issue by StevenGrysolle** [digipolisantwerp/chatbot_widget_ng1#8]
Opmerkingen van gebruikers/testpanel Klanten en OS Jasmin De Rycker
In de chat sessie worden:
- de replieken van de chatbot LINKS uitgelijnd.
- de antwoorden/vragen van de gebruiker RECHTS uitgelijnd.
- De knoppen die door de chat bot worden gepubliceerd zijn momenteel gecentreerd op de pagina. => gelieve deze net zoals de replieken van de chat bot LINKs uit te lijnen.

en/of eventueel UX-er raadplegen om userfriendlyness te verhogen.

**Comment by jsebrech** [comment]
@TriangleJuice wat denk jij dat hier het beste is?

**Comment by TriangleJuice** [comment]
@StevenGrysolle cc @jsebrech 
Het centreren van de knoppen is een weloverwogen beslissing geweest van het UX-team. Het is een state die zich tussen vraag en antwoord situeert, vandaar dat de knoppen gecentreerd werden.

Als een project wil afwijken van die standaard, dan kan dat, mits de huisstijl van de stad niet in het gedrang komt (wat hier niet het geval is), maar dan moeten ze deze wijziging wel zelf implementeren.

Ik raad wel nog steeds aan om niet af te wijken van de reeds gedefinieerde standaard, zodat alle chatbots er voor alle gebruikers hetzelfde uitzien.

**Comment by jsebrech** [comment]
Issue afgesloten omdat dit op projectniveau gedaan kan worden.
